apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-group-upgrades-operator-sub
  namespace: openshift-talo
spec:
  channel: preview
  installPlanApproval: Automatic
  name: cluster-group-upgrades-operator
  source: ran-operators
  sourceNamespace: openshift-marketplace
